#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$sequence = new ArchFizz\SequenceIterator(new ArchFizz\ArchFizzBuzz());

$iterations = isset($argv) && isset($argv[1]) ? (int) $argv[1] : 15;

print $sequence->iterate($iterations);

print PHP_EOL;

exit(0);
